### ISSUE TITLE
api error

### ISSUE THREAD

**Issue by CaoHoa1** [dadaloop82/HASS_AppDeamon_SwitchPredictor#6]
api error
  my config file
api:
and I get this error Traceback (most recent call last):
   File "\\192.168.1.58\config\appdaemon\apps\hass_predictswitch.py", line 46, in <module>
     import hassapi as hass
ModuleNotFoundError: No module named 'hassapi'
[Finished in 281ms]

**Comment by CaoHoa1** [comment]
do you use xgboost algorithm?

**Comment by dadaloop82** [comment]
> api error my config file api: and I get this error Traceback (most recent call last): File "\192.168.1.58\config\appdaemon\apps\hass_predictswitch.py", line 46, in import hassapi as hass ModuleNotFoundError: No module named 'hassapi' [Finished in 281ms]

Have you tried these last few days?
Do you still get the error?

**Comment by dadaloop82** [comment]
> do you use xgboost algorithm?

Not at the moment, I'm focusing on optimized data collection.
